// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUARwkDV-jLDGdYd_qM7lImTUHEdSfAjw',
    appId: '1:1012897877829:android:559acf302af75924aff82c',
    messagingSenderId: '1012897877829',
    projectId: 'despesas-pessoais-76cbd',
    databaseURL: 'https://despesas-pessoais-76cbd-default-rtdb.firebaseio.com',
    storageBucket: 'despesas-pessoais-76cbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6195neHaTo_EiILa9NYWD_5ZYh2dGT0',
    appId: '1:1012897877829:ios:62735545aac121e9aff82c',
    messagingSenderId: '1012897877829',
    projectId: 'despesas-pessoais-76cbd',
    databaseURL: 'https://despesas-pessoais-76cbd-default-rtdb.firebaseio.com',
    storageBucket: 'despesas-pessoais-76cbd.firebasestorage.app',
    androidClientId: '1012897877829-od8k73hqquvuf6c2f7mebefb201nge4d.apps.googleusercontent.com',
    iosClientId: '1012897877829-0k81l4sqra0ree12g9u6o37rho2gkjk6.apps.googleusercontent.com',
    iosBundleId: 'br.com.guilhermeribeiro.tarefasgeo',
  );
}
